- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 10800 # 3 hours
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 3600 # 1 hours
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 10800 # 3 hours
    - !type:AgeRequirement
      requiredAge: 24
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Engineering
  wage: 70
  #end-backmen: currency

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
    socks: ClothingUnderwearSocksSeniorEngineer
