- type: job
  id: SeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobSeniorPhysician
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 7200 # 2 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200 # 2 hours
    - !type:AgeRequirement
      requiredAge: 24
  startingGear: SeniorPhysicianGear
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry
  - Paramedic
  - Coroner
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Medical
  wage: 70
  #end-backmen: currency

- type: startingGear
  id: SeniorPhysicianGear
  equipment:
    shoes: ClothingShoesColorBlack
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    socks: ClothingUnderwearSocksSeniorPhysician
