- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: true
  objective: roles-antag-thief-objective
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 14400 # 4 hours
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 3600 # 1 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 3600 # 1 hours
    - !type:DepartmentTimeRequirement
      department: Science
      time: 1800 # 0,5 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 3600 # 1 hrs
  # guides: [ Thieves ] # DS14: disabled due to lack of localization

- type: startingGear
  id: ThiefGear
  storage:
    back:
    - ThiefBeacon
    - ToolboxThief
    - ClothingHandsChameleonThief
